spring:
  datasource:
    url: jdbc:h2:mem:public;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    open-in-view: false


  flyway:
    url: jdbc:h2:mem:public;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;
    user: sa
    password:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration/{vendor}

  h2:
    console:
      enabled: true
